# Generated by Django 5.1.1 on 2024-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='address',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='userr',
            name='city',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='userr',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='userr',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userr',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userr',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userr',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userr',
            name='state',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
