# Generated by Django 5.1.1 on 2024-09-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_userr_address_userr_city_userr_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userr',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
