# Generated by Django 5.1.1 on 2024-09-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_userr_is_admin_alter_userr_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userr',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
