# Generated by Django 5.1.1 on 2024-12-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='listing_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
