# Generated by Django 5.1.1 on 2024-12-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_listing_fee_paid_vendor_subscription_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='listing_fee_paid',
        ),
    ]
